import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ArrowLeft, Shield, Database, ExternalLink } from 'lucide-react'

export default function NCTPage() {
  return (
    <div className="min-h-screen bg-slate-950 py-8">
      <div className="container mx-auto px-4">
        {/* Breadcrumb */}
        <div className="mb-8">
          <Button asChild variant="ghost" className="text-slate-400 hover:text-white">
            <Link href="/subunits">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Subunits
            </Link>
          </Button>
        </div>

        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-blue-500 to-blue-600 rounded-2xl mb-6">
            <Shield className="h-10 w-10 text-white" />
          </div>
          <h1 className="text-4xl font-bold text-white mb-4">NCT</h1>
          <p className="text-xl text-slate-400 mb-2">Nicastrin</p>
          <p className="text-slate-300 max-w-3xl mx-auto">
            The substrate receptor subunit of the γ-secretase complex that recognizes and binds to 
            the stub peptides generated by α- or β-secretase cleavage of substrates. NCT plays a 
            crucial role in substrate selectivity and binding.
          </p>
        </div>

        {/* Key Information */}
        <div className="grid lg:grid-cols-3 gap-8 mb-12">
          <Card className="bg-slate-800/50 border-slate-700">
            <CardHeader>
              <CardTitle className="text-white flex items-center">
                <Database className="h-5 w-5 mr-2" />
                Basic Information
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div>
                <span className="text-slate-400 text-sm">UniProt ID:</span>
                <p className="text-white font-mono">Q92542</p>
              </div>
              <div>
                <span className="text-slate-400 text-sm">Length:</span>
                <p className="text-white">709 amino acids</p>
              </div>
              <div>
                <span className="text-slate-400 text-sm">Molecular Weight:</span>
                <p className="text-white">~78 kDa</p>
              </div>
              <div>
                <span className="text-slate-400 text-sm">Type:</span>
                <p className="text-white">Type I transmembrane glycoprotein</p>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-slate-800/50 border-slate-700">
            <CardHeader>
              <CardTitle className="text-white">Functional Role</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div>
                <span className="text-slate-400 text-sm">Primary Function:</span>
                <p className="text-white">Substrate Recognition</p>
              </div>
              <div>
                <span className="text-slate-400 text-sm">Binding Specificity:</span>
                <p className="text-white">Stub peptides</p>
              </div>
              <div>
                <span className="text-slate-400 text-sm">Key Motif:</span>
                <p className="text-white font-mono">DYIGS</p>
              </div>
              <div>
                <span className="text-slate-400 text-sm">Glycosylation:</span>
                <p className="text-white">Extensively glycosylated</p>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-slate-800/50 border-slate-700">
            <CardHeader>
              <CardTitle className="text-white">Conservation</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <div className="flex justify-between items-center mb-2">
                  <span className="text-slate-300">Overall Conservation</span>
                  <span className="text-cyan-400 font-bold">91.8%</span>
                </div>
                <div className="w-full bg-slate-700 rounded-full h-2">
                  <div className="bg-gradient-to-r from-blue-500 to-cyan-500 h-2 rounded-full" style={{ width: '91.8%' }}></div>
                </div>
              </div>
              <p className="text-slate-400 text-sm">
                High conservation in substrate-binding regions across vertebrates.
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Functional Domains */}
        <Card className="bg-slate-800/50 border-slate-700 mb-8">
          <CardHeader>
            <CardTitle className="text-white">Structural Domains & Key Sites</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h4 className="text-lg font-semibold text-white mb-4">Key Functional Sites</h4>
                <div className="space-y-3">
                  <div className="p-3 bg-slate-900/50 rounded-lg">
                    <div className="flex justify-between items-center mb-1">
                      <span className="font-mono text-cyan-400">DYIGS motif</span>
                      <span className="text-xs text-slate-500">333-337</span>
                    </div>
                    <p className="text-slate-300 text-sm">Critical for substrate binding and recognition</p>
                  </div>
                  <div className="p-3 bg-slate-900/50 rounded-lg">
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-white">Signal Peptide</span>
                      <span className="text-xs text-slate-500">1-26</span>
                    </div>
                    <p className="text-slate-300 text-sm">Directs protein to endoplasmic reticulum</p>
                  </div>
                </div>
              </div>
              
              <div>
                <h4 className="text-lg font-semibold text-white mb-4">Structural Regions</h4>
                <div className="space-y-3">
                  <div className="p-3 bg-slate-900/50 rounded-lg">
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-white">Extracellular Domain</span>
                      <span className="text-xs text-slate-500">27-665</span>
                    </div>
                    <p className="text-slate-300 text-sm">Large domain for substrate recognition</p>
                  </div>
                  <div className="p-3 bg-slate-900/50 rounded-lg">
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-white">Transmembrane Domain</span>
                      <span className="text-xs text-slate-500">666-686</span>
                    </div>
                    <p className="text-slate-300 text-sm">Single-pass membrane anchor</p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Sequence Information */}
        <Card className="bg-slate-800/50 border-slate-700 mb-8">
          <CardHeader>
            <CardTitle className="text-white">Sequence Information</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="bg-slate-900 p-4 rounded-lg overflow-x-auto">
              <p className="text-xs text-slate-400 mb-2">Human NCT (UniProt: Q92542)</p>
              <div className="font-mono text-sm text-slate-300 break-all">
                <span className="text-cyan-400">MATAGGGSGAD</span>
                <span className="text-slate-300">PGSRGLLRLL</span>
                <span className="text-green-400">SFCVLLAGLC</span>
                <span className="text-slate-300">RGNSVERKIY</span>
                <span className="text-yellow-400">IPLNKTAPCV</span>
                <span className="text-slate-300">RLLNATHQIG</span>
                <br />
                <span className="text-slate-300">CQSSISGDTG</span>
                <span className="text-red-400">VIHVVEKEED</span>
                <span className="text-slate-300">LQWVLTDGPN</span>
                <span className="text-blue-400">PPYMVLLESK</span>
                <span className="text-slate-300">HFTRDLMEKL</span>
                <span className="text-purple-400">KGRTSRIAGL</span>
                <br />
                <span className="text-slate-300">...</span>
              </div>
              <p className="text-xs text-slate-500 mt-2">
                Colors indicate different structural regions: 
                <span className="text-cyan-400 ml-2">Signal peptide</span>
                <span className="text-green-400 ml-2">Extracellular</span>
                <span className="text-red-400 ml-2">Transmembrane</span>
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Glycosylation Sites */}
        <Card className="bg-slate-800/50 border-slate-700 mb-8">
          <CardHeader>
            <CardTitle className="text-white">Post-translational Modifications</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h4 className="text-lg font-semibold text-white mb-4">N-linked Glycosylation</h4>
                <p className="text-slate-300 mb-3">
                  NCT is extensively glycosylated, which affects its stability and function within the γ-secretase complex.
                </p>
                <div className="space-y-2">
                  <div className="flex justify-between items-center p-2 bg-slate-900/50 rounded">
                    <span className="text-slate-300">Predicted sites:</span>
                    <span className="text-cyan-400">15+</span>
                  </div>
                  <div className="flex justify-between items-center p-2 bg-slate-900/50 rounded">
                    <span className="text-slate-300">Functional impact:</span>
                    <span className="text-green-400">High</span>
                  </div>
                </div>
              </div>
              
              <div>
                <h4 className="text-lg font-semibold text-white mb-4">Other Modifications</h4>
                <div className="space-y-3">
                  <div className="p-3 bg-slate-900/50 rounded-lg">
                    <span className="text-white font-semibold">Proteolytic Processing</span>
                    <p className="text-slate-300 text-sm mt-1">
                      May undergo limited proteolysis during complex maturation
                    </p>
                  </div>
                  <div className="p-3 bg-slate-900/50 rounded-lg">
                    <span className="text-white font-semibold">Phosphorylation</span>
                    <p className="text-slate-300 text-sm mt-1">
                      Potential regulatory phosphorylation sites identified
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button asChild className="bg-cyan-600 hover:bg-cyan-700 text-white">
            <Link href="/species">
              Compare Across Species
            </Link>
          </Button>
          <Button asChild variant="outline" className="border-slate-600 text-slate-300 hover:bg-slate-700">
            <Link href="/evolution">
              View Evolution Tree
            </Link>
          </Button>
          <Button asChild variant="outline" className="border-slate-600 text-slate-300 hover:bg-slate-700">
            <a href="https://www.uniprot.org/uniprot/Q92542" target="_blank" rel="noopener noreferrer">
              UniProt Entry
              <ExternalLink className="ml-2 h-4 w-4" />
            </a>
          </Button>
        </div>
      </div>
    </div>
  )
}
